version: '3'
services:
  app:
    build: .
    command: bash -c "python ./manage.py migrate --noinput
      && python manage.py collectstatic --noinput
      && gunicorn project.wsgi:application --bind :8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
          - media-data:/app/media

  postgres:
    image: postgres:14.4
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local
  media-data:
    driver: local
